// Command gen-sdd-agent-digests writes the registry of every native SDD
// sub-agent template a Gentle AI release shipped, keyed by family and file
// name, so sync and install can prove a retired agent is Gentle AI's own
// render (issues #5157, #5253). Digests use legacyassets.NormalizeSDDAgent,
// the same function ownership checks run on installed files.
//
// SDD was retired in v4.0.0, so the release set is closed. Fetch tags first:
//
//	git fetch --tags
//	go generate ./internal/components/legacyassets/
//
// The generator refuses an incomplete tag set, and it proves the
// normalization against every release's golden renders: each
// testdata/golden/sdd-<family>-agent-<name>.golden must normalize to a digest
// of that same release's template.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path"
	"slices"
	"strings"

	"github.com/gentleman-programming/gentle-ai/v4/internal/components/legacyassets"
)

var anchors = []string{"v1.10.0", "v3.7.0", "v4.0.0"}

type row struct{ first, last string }

func main() {
	if len(os.Args) != 2 {
		fail("usage: gen-sdd-agent-digests <output.go>")
	}
	root = strings.TrimSpace(git("rev-parse", "--show-toplevel"))
	tags := strings.Fields(git("-c", "versionsort.suffix=-", "tag", "-l", "v*", "--sort=v:refname"))
	for _, anchor := range anchors {
		if !slices.Contains(tags, anchor) {
			fail("release tag %s missing; the local tag set is incomplete; run git fetch --tags", anchor)
		}
	}
	families := sddAgentFamilies()
	blobDigest := map[string]string{}
	ranges := map[string]map[string]*row{}
	order := map[string][]string{}
	for _, tag := range tags {
		templates := map[string]string{}
		for _, line := range strings.Split(git("ls-tree", "-r", tag, "--", "internal/assets"), "\n") {
			fields := strings.Fields(line)
			if len(fields) != 4 || fields[1] != "blob" {
				continue
			}
			blob, file := fields[2], fields[3]
			// internal/assets/<family>/agents/sdd-*
			parts := strings.Split(file, "/")
			if len(parts) != 5 || !families[parts[2]] || parts[3] != "agents" || !strings.HasPrefix(parts[4], "sdd-") {
				continue
			}
			family, name := parts[2], parts[4]
			digest, ok := blobDigest[blob]
			if !ok {
				digest = legacyassets.SDDAgentDigest(git("cat-file", "blob", blob))
				blobDigest[blob] = digest
			}
			key := family + "/" + name
			templates[key] = digest
			if ranges[key] == nil {
				ranges[key] = map[string]*row{}
			}
			if r := ranges[key][digest]; r != nil {
				r.last = tag
			} else {
				ranges[key][digest] = &row{tag, tag}
				order[key] = append(order[key], digest)
			}
		}
		verifyGoldens(tag, templates)
	}
	fmt.Fprintf(os.Stderr, "gen-sdd-agent-digests: %d golden renders verified across %d releases\n", verifiedGoldens, len(tags))
	if len(order) == 0 {
		fail("no SDD agent templates found in any release")
	}
	keys := make([]string, 0, len(order))
	for key := range order {
		keys = append(keys, key)
	}
	slices.Sort(keys)
	var b bytes.Buffer
	b.WriteString("// Code generated by scripts/gen-sdd-agent-digests; DO NOT EDIT.\n\npackage legacyassets\n\n")
	b.WriteString("// releasedSDDAgentDigests maps <family>/<file> to the normalized digest of\n// every native SDD sub-agent template a Gentle AI release shipped.\n")
	b.WriteString("var releasedSDDAgentDigests = map[string][]string{\n")
	for _, key := range keys {
		fmt.Fprintf(&b, "%q: {\n", key)
		for _, digest := range order[key] {
			r := ranges[key][digest]
			span := r.first
			if r.last != r.first {
				span += " to " + r.last
			}
			fmt.Fprintf(&b, "%q, // %s\n", digest, span)
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		fail("format registry: %v", err)
	}
	if err := os.WriteFile(os.Args[1], formatted, 0o644); err != nil {
		fail("write registry: %v", err)
	}
}

var verifiedGoldens int

// verifyGoldens fails generation when a release's own golden render of an
// SDD agent does not normalize to that release's template.
func verifyGoldens(tag string, templates map[string]string) {
	for _, line := range strings.Split(git("ls-tree", "-r", "--name-only", tag, "--", "testdata/golden"), "\n") {
		name := path.Base(line)
		for family := range sddAgentFamilies() {
			prefix := "sdd-" + family + "-agent-"
			if !strings.HasPrefix(name, prefix) || !strings.HasSuffix(name, ".golden") {
				continue
			}
			key := family + "/" + strings.TrimSuffix(strings.TrimPrefix(name, prefix), ".golden") + ".md"
			want, ok := templates[key]
			if !ok {
				continue
			}
			if got := legacyassets.SDDAgentDigest(git("show", tag+":"+line)); got != want {
				fail("%s: golden %s does not normalize to its template %s", tag, line, key)
			}
			verifiedGoldens++
		}
	}
}

func sddAgentFamilies() map[string]bool {
	families := map[string]bool{}
	for _, family := range legacyassets.SDDAgentFamilies {
		families[family] = true
	}
	return families
}

// root is the repository top level; pathspecs are relative to it.
var root string

func git(args ...string) string {
	cmd := exec.Command("git", args...)
	cmd.Dir = root
	var stderr bytes.Buffer
	cmd.Stderr = &stderr
	out, err := cmd.Output()
	if err != nil {
		fail("git %s: %v\n%s", strings.Join(args, " "), err, stderr.String())
	}
	return string(out)
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-sdd-agent-digests: "+format+"\n", args...)
	os.Exit(1)
}
