package cli

import (
	"errors"
	"strings"

	"github.com/gentleman-programming/gentle-ai/v2/internal/model"
)

const reviewImmutableTransportUnsupportedCode = "immutable_review_transport_unsupported"

var reviewImmutableTransportUnsupportedReason = reviewPreflightReason{
	Code:       reviewImmutableTransportUnsupportedCode,
	Message:    "The active runtime cannot provide immutable receipt-review transport.",
	NextAction: "stop",
}

const reviewRuntimeIdentityUnresolvedCode = "runtime_identity_unresolved"

// reviewRuntimeIdentityUnresolvedReason classifies a negotiated route that did
// not carry exactly one `--agent` token. That is a malformed or stale route,
// not a statement about any runtime's transport: classifying it as
// `immutable_review_transport_unsupported` named a capability the facade never
// evaluated and left the caller with a terminal stop and nothing to run
// (issue #2242). The route is regenerated by `gentle-ai sync`, so the honest
// exit is "correct the request you sent", which stays retry-safe.
var reviewRuntimeIdentityUnresolvedReason = reviewPreflightReason{
	Code:       reviewRuntimeIdentityUnresolvedCode,
	Message:    "The negotiated review route did not carry exactly one runtime identity; re-run it with the single exact --agent token from the generated route.",
	NextAction: "correct_request",
}

type reviewImmutableTransport string

const (
	reviewImmutableTransportUnsupported         reviewImmutableTransport = "unsupported"
	reviewImmutableTransportClaudePromptCarried reviewImmutableTransport = "claude_prompt_carried"
)

type reviewImmutableRuntimePolicy struct {
	Eligible  bool
	Transport reviewImmutableTransport
}

// reviewImmutableRuntimeCapability is the compiled receipt-review boundary.
// Generic adapter features and caller-supplied claims cannot expand it.
func reviewImmutableRuntimeCapability(agent model.AgentID) reviewImmutableRuntimePolicy {
	switch agent {
	case model.AgentClaudeCode:
		return reviewImmutableRuntimePolicy{Eligible: true, Transport: reviewImmutableTransportClaudePromptCarried}
	case model.AgentCodex:
		return reviewImmutableRuntimePolicy{Eligible: true, Transport: reviewImmutableTransportUnsupported}
	case model.AgentOpenCode:
		// #2076 owns a future documented exact child-session binding.
		return reviewImmutableRuntimePolicy{Eligible: true, Transport: reviewImmutableTransportUnsupported}
	default:
		return reviewImmutableRuntimePolicy{Transport: reviewImmutableTransportUnsupported}
	}
}

func (capability reviewImmutableRuntimePolicy) supportsImmutableReceiptReview() bool {
	return capability.Transport == reviewImmutableTransportClaudePromptCarried
}

// reviewRuntimeWithImmutableTransport accepts only the exact compiled runtime
// identities. It never selects a substitute transport for an unsupported one.
func reviewRuntimeWithImmutableTransport(agent string) (model.AgentID, error) {
	if strings.TrimSpace(agent) == "" || strings.TrimSpace(agent) != agent {
		// refusal:by-design world-action: an unknown runtime cannot safely receive immutable review authority
		return "", errors.New("the active review runtime is unknown")
	}
	identity := model.AgentID(agent)
	capability := reviewImmutableRuntimeCapability(identity)
	if !capability.Eligible {
		// refusal:by-design world-action: runtimes outside the fixed RDD policy cannot receive immutable review authority
		return "", errors.New("the active runtime is not eligible for immutable receipt review")
	}
	if !capability.supportsImmutableReceiptReview() {
		// refusal:by-design world-action: unsupported transport cannot bind immutable evidence or capture an admissible result
		return "", errors.New("the active runtime lacks immutable receipt-review transport")
	}
	return identity, nil
}

func reviewRuntimeAgentCount(args []string) int {
	count := 0
	for index := 0; index < len(args); index++ {
		argument := args[index]
		if argument == "--" {
			break
		}
		nameValue := strings.TrimPrefix(strings.TrimPrefix(argument, "-"), "-")
		if nameValue == argument || nameValue == "" {
			continue
		}
		name, hasValue := nameValue, false
		if separator := strings.IndexByte(nameValue, '='); separator >= 0 {
			name, hasValue = nameValue[:separator], true
		}
		if name != "agent" {
			continue
		}
		count++
		if !hasValue {
			index++
		}
	}
	return count
}
