package reviewassets

import (
	"bytes"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"sort"
	"strings"
	"testing"

	"github.com/gentleman-programming/gentle-ai/v4/internal/model"
)

var updateLegacySDDHashes = flag.Bool("update-legacy-sdd-hashes", false, "regenerate legacy_sdd_hashes.go from the v3 release tags in git history")

const legacySDDHashesFile = "legacy_sdd_hashes.go"

// TestLegacySDDAgentHashesMatchV3ReleaseHistory rebuilds the known-render
// table from every v3 release tag and requires legacy_sdd_hashes.go to match.
// Shallow clones without tags skip; regenerate with -update-legacy-sdd-hashes.
func TestLegacySDDAgentHashesMatchV3ReleaseHistory(t *testing.T) {
	if testing.Short() {
		t.Skip("reads git history")
	}
	if _, err := exec.LookPath("git"); err != nil {
		t.Skip("git unavailable")
	}
	out, err := exec.Command("git", "tag", "--list", "v3.*", "--sort=version:refname").Output()
	tags := strings.Fields(string(out))
	if err != nil || len(tags) == 0 {
		if *updateLegacySDDHashes {
			t.Fatalf("no v3 release tags available to regenerate %s: %v", legacySDDHashesFile, err)
		}
		t.Skipf("v3 release tags unavailable (shallow clone?): %v", err)
	}

	want := make(map[string]map[string][]string)
	for _, tag := range tags {
		for _, name := range LegacySDDNativeAgentManifest[model.AgentClaudeCode] {
			template, err := exec.Command("git", "show", tag+":internal/assets/claude/agents/"+name).Output()
			if err != nil {
				continue // Not shipped in this release.
			}
			hash := installedHash([]byte(normalizeLegacySDDAgent(renderLegacySDDTemplate(string(template)))))
			if want[name] == nil {
				want[name] = make(map[string][]string)
			}
			want[name][hash] = append(want[name][hash], tag)
		}
	}
	for _, name := range LegacySDDNativeAgentManifest[model.AgentClaudeCode] {
		if len(want[name]) == 0 {
			t.Fatalf("no v3 release shipped %s; drop it from LegacySDDNativeAgentManifest", name)
		}
	}

	if *updateLegacySDDHashes {
		if err := os.WriteFile(legacySDDHashesFile, renderLegacySDDHashesFile(t, want), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	for name, hashes := range want {
		for hash, provenance := range hashes {
			if got, ok := legacySDDAgentHashes[name][hash]; !ok || got != strings.Join(provenance, " ") {
				t.Errorf("%s: hash %s = %q, want %q; rerun with -update-legacy-sdd-hashes", name, hash, got, strings.Join(provenance, " "))
			}
		}
		if len(legacySDDAgentHashes[name]) != len(hashes) {
			t.Errorf("%s: table has %d hashes, history has %d", name, len(legacySDDAgentHashes[name]), len(hashes))
		}
	}
	if len(legacySDDAgentHashes) != len(want) {
		t.Errorf("table covers %d agents, history has %d", len(legacySDDAgentHashes), len(want))
	}
}

// renderLegacySDDTemplate fills the v3 template placeholders the way v3
// sdd.Inject did. The option-dependent values are dropped again by
// normalizeLegacySDDAgent, so any valid choice yields the same hash.
func renderLegacySDDTemplate(template string) string {
	template = strings.ReplaceAll(template, "{{CLAUDE_MODEL}}", "sonnet")
	template = strings.ReplaceAll(template, "{{CLAUDE_EFFORT_FRONTMATTER}}\r\n", "")
	template = strings.ReplaceAll(template, "{{CLAUDE_EFFORT_FRONTMATTER}}\n", "")
	template = strings.ReplaceAll(template, "{{CLAUDE_EFFORT_FRONTMATTER}}", "")
	return engramToolPlaceholder.ReplaceAllString(template, "mcp__engram__$1, mcp__plugin_engram_engram__$1")
}

func renderLegacySDDHashesFile(t *testing.T, table map[string]map[string][]string) []byte {
	t.Helper()
	var b bytes.Buffer
	b.WriteString("// Code generated by go test ./internal/components/reviewassets -run TestLegacySDDAgentHashesMatchV3ReleaseHistory -update-legacy-sdd-hashes; DO NOT EDIT.\n\n")
	b.WriteString("package reviewassets\n\n")
	b.WriteString("// legacySDDAgentHashes maps each legacy SDD agent to the sha256 of its\n")
	b.WriteString("// normalized v3 render (see normalizeLegacySDDAgent) and the release tags\n")
	b.WriteString("// whose internal/assets/claude/agents template produced it.\n")
	b.WriteString("var legacySDDAgentHashes = map[string]map[string]string{\n")
	names := make([]string, 0, len(table))
	for name := range table {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		fmt.Fprintf(&b, "%q: {\n", name)
		hashes := make([]string, 0, len(table[name]))
		for hash := range table[name] {
			hashes = append(hashes, hash)
		}
		sort.Strings(hashes)
		for _, hash := range hashes {
			fmt.Fprintf(&b, "%q: %q,\n", hash, strings.Join(table[name][hash], " "))
		}
		b.WriteString("},\n")
	}
	b.WriteString("}\n")
	formatted, err := format.Source(b.Bytes())
	if err != nil {
		t.Fatal(err)
	}
	return formatted
}

func TestNormalizeLegacySDDAgentDropsOnlyOptionDependentParts(t *testing.T) {
	t.Parallel()

	base := normalizeLegacySDDAgent(renderV3ClaudeSDDAgent(t, "sdd-apply.md", "sonnet", "", ""))
	for _, tc := range []struct {
		name, content string
		same          bool
	}{
		{name: "opus, max effort, codegraph", content: renderV3ClaudeSDDAgent(t, "sdd-apply.md", "opus", "max", "guidance"), same: true},
		{name: "CRLF line endings", content: strings.ReplaceAll(renderV3ClaudeSDDAgent(t, "sdd-apply.md", "haiku", "", ""), "\n", "\r\n"), same: true},
		{name: "other agent", content: renderV3ClaudeSDDAgent(t, "sdd-verify.md", "sonnet", "", "")},
		{name: "extra frontmatter key", content: strings.Replace(renderV3ClaudeSDDAgent(t, "sdd-apply.md", "sonnet", "", ""), "tools:", "color: red\ntools:", 1)},
		{name: "extra tool grant", content: strings.Replace(renderV3ClaudeSDDAgent(t, "sdd-apply.md", "sonnet", "", ""), "Bash,", "Bash, WebFetch,", 1)},
		{name: "unmanaged section", content: renderV3ClaudeSDDAgent(t, "sdd-apply.md", "sonnet", "", "") + "<!-- gentle-ai:mine -->\nx\n<!-- /gentle-ai:mine -->\n"},
	} {
		if got := normalizeLegacySDDAgent(tc.content) == base; got != tc.same {
			t.Errorf("%s: normalized equal = %t, want %t", tc.name, got, tc.same)
		}
	}
}
