// Code generated by go test ./internal/components/reviewassets -run TestLegacySDDAgentHashesMatchV3ReleaseHistory -update-legacy-sdd-hashes; DO NOT EDIT.

package reviewassets

// legacySDDAgentHashes maps each legacy SDD agent to the sha256 of its
// normalized v3 render (see normalizeLegacySDDAgent) and the release tags
// whose internal/assets/claude/agents template produced it.
var legacySDDAgentHashes = map[string]map[string]string{
	"sdd-apply.md": {
		"9fabf15b05a55f12d6e6cf2e2143009ed35e89a654f5fe26deb9d637e516a387": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-archive.md": {
		"79bb2e25beb48e4ed3edd5f2686d8b1a66683b611f9dbaf6507c799215098905": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-design.md": {
		"617dbbc42fb72ef25c64bad864825db26752d9885135e93943e6f80e270de1e5": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-explore.md": {
		"51fd9077ad73add9fd9ff87df9cb61b831fc58f34970865de0419f0f5f2b8dd5": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-init.md": {
		"8666400c48ca126ff562a1623b69d0c158a8433b1f82c2a664d8a5181712ae9d": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-onboard.md": {
		"2af5b2cc054d3bca503b4557ebe1170e26fb06fef821e514fc77933125363c83": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-propose.md": {
		"5d28fb38927a8a2c4e442b43bf9ed3f444289472b7bb29f09826442bbeb6a407": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-research.md": {
		"bbcae2885a7b68de957fc2cbe0f93f23dfa22ed576ff81d6fcbeb73c2f2d5ea1": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-spec.md": {
		"24de53719746455dd434ffe55bf29739765243011ade93d652868c8c8c653bbc": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-tasks.md": {
		"73ad000cc588c591f97b844a4dba6dbd542e915abbfa4d2a66a7b0768edb849b": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
	"sdd-verify.md": {
		"2736cf80bb140e895773945d211386c451292560219db6c387688b1888c6a7ce": "v3.0.0 v3.0.1 v3.0.2 v3.1.0 v3.2.1 v3.3.0 v3.4.0 v3.5.0 v3.6.0 v3.6.1 v3.7.0",
	},
}
