#!/usr/bin/env bash
# Generate the SHA-256 registry of every managed OpenCode plugin byte sequence
# Gentle AI has shipped, so an upgrade can recognize its own earlier plugins as
# owned (issue #5185) while still preserving bytes no release ever wrote.
#
# Sources: the plugin assets at every local `v*` release tag plus the assets in
# the current working tree (not yet released). Fetch tags first:
#
#   git fetch --tags
#   go generate ./internal/components/opencoderuntimeplugins/
#
# TestReleasedPluginDigestsCoverEmbeddedAssets fails when an embedded asset
# changes without regenerating, so the registry only ever grows.
set -euo pipefail

root=$(git rev-parse --show-toplevel)
names='background-agents.ts model-variants.ts opencode-review-transport.ts review-result-artifacts.ts skill-registry.ts'
dirs='internal/assets/opencode/plugins internal/assets/opencode/plugins-v2'

if command -v sha256sum >/dev/null; then
	sha256() { sha256sum | cut -d' ' -f1; }
else
	sha256() { shasum -a 256 | cut -d' ' -f1; }
fi

tags=$(git -C "$root" -c versionsort.suffix=- tag -l 'v*' --sort=v:refname)
if [ -z "$tags" ]; then
	echo "no v* release tags found; run git fetch --tags" >&2
	exit 1
fi

# rows: <name> <asset dir> <source> <blob>, in release order.
rows=$(
	for tag in $tags; do
		# shellcheck disable=SC2086
		git -C "$root" ls-tree -r "$tag" -- $dirs | while read -r _ _ blob path; do
			echo "${path##*/} ${path%/*} $tag $blob"
		done
	done
	for dir in $dirs; do
		for name in $names; do
			if [ -f "$root/$dir/$name" ]; then
				echo "$name $dir unreleased $(git -C "$root" hash-object "$root/$dir/$name")"
			fi
		done
	done
)

# Digest each distinct blob once; the working tree is LF-normalized by
# .gitattributes, so blob bytes are the bytes every release embedded.
digests=$(echo "$rows" | cut -d' ' -f4 | sort -u | while read -r blob; do
	echo "$blob $(git -C "$root" cat-file blob "$blob" | sha256)"
done)

# Write to the optional output path, otherwise stdout.
if [ $# -gt 0 ]; then
	exec >"$1"
fi
{
	echo '// Code generated by scripts/gen-opencode-plugin-digests.sh; DO NOT EDIT.'
	echo
	echo 'package opencoderuntimeplugins'
	echo
	echo '// releasedPluginDigests maps each managed or retired OpenCode plugin name to'
	echo '// the SHA-256 of every byte sequence a Gentle AI release shipped for it.'
	echo 'var releasedPluginDigests = map[string][]string{'
	awk -v names="$names" '
		NR == FNR { digest[$1] = $2; next }
		{
			split($2, parts, "/"); dir = parts[length(parts)] "/"
			key = $1 SUBSEP digest[$4]
			if (!(key in seen)) { seen[key] = 1; order[$1] = order[$1] " " digest[$4] }
			if (index(dirsOf[key] " ", " " dir " ") == 0) dirsOf[key] = dirsOf[key] " " dir
			if ($3 != "unreleased") { if (!(key in first)) first[key] = $3; last[key] = $3 }
		}
		END {
			n = split(names, list, " ")
			for (i = 1; i <= n; i++) {
				name = list[i]
				if (order[name] == "") continue
				printf "\t\"%s\": {\n", name
				m = split(order[name], sums, " ")
				for (j = 1; j <= m; j++) {
					key = name SUBSEP sums[j]
					span = "unreleased"
					if (key in first) span = first[key] (first[key] == last[key] ? "" : " to " last[key])
					printf "\t\t\"%s\", //%s %s\n", sums[j], dirsOf[key], span
				}
				printf "\t},\n"
			}
		}
	' <(echo "$digests") <(echo "$rows")
	echo '}'
}
